"""Add cycle table

Revision ID: 491129f677f8
Revises: 08944b933bb9
Create Date: 2024-12-12 17:51:37.724788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491129f677f8'
down_revision: Union[str, None] = '08944b933bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('buy_date', sa.DateTime(), nullable=False),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('sell_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_klines_close_time', table_name='klines')
    op.drop_index('idx_klines_open_time', table_name='klines')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_klines_open_time', 'klines', ['open_time'], unique=False)
    op.create_index('idx_klines_close_time', 'klines', ['close_time'], unique=False)
    op.drop_table('cycles')
    # ### end Alembic commands ###
